# Puerto del servidor (Render lo detectará, pero dejamos el 8081 por defecto)
server.port=8081

# ---- CONFIGURACIÓN DE NEON (BASE DE DATOS REAL) ----
# Usamos la URL de pooling para que no haya problemas de conexiones máximas
spring.datasource.url=jdbc:postgresql://ep-lucky-hill-alz6w3e1-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l3jkOXmA1Grg
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- CONFIGURACIÓN DE JPA / HIBERNATE ----
# 'update' creará las tablas automáticamente en Neon si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Mostrar los logs de SQL para que en Render veas si guarda bien
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE